version: '3.8'
services:
  redpanda:
    image: 'docker.vectorized.io/vectorized/redpanda:latest'
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false --advertise-kafka-addr redpanda:9092
    ports:
      - '9092:9092'
      - '9644:9644'
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4096M
        reservations:
          memory: 4096M
  chameleon:
    image: chameleon:0.1
    ports:
      - "3000:3000"
    volumes:
      - ./config/:/config/
      - ./data/:/data/
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          memory: 512M

