
topic:
	docker exec -it redpanda_redpanda_1  rpk topic create topic-A --replicas 1

list:
	docker exec -it redpanda_redpanda_1  rpk topic list

consume:
	docker exec -it redpanda_redpanda_1 rpk topic consume topic-A