version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
        reservations:
          memory: 1024M
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://host.docker.internal:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4096M
        reservations:
          memory: 4096M
    depends_on:
      - zookeeper
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9001:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka

  chameleon:
    image: chameleon:0.1
    ports:
      - "3000:3000"
    volumes:
      - ./config/:/config/
      - ./data/:/data/
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          memory: 512M
