version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9001:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka

  chameleon:
    image: naughtytao/chameleon:0.1.20210913
    ports:
      - "3000:3000"
    volumes:
      - ./config/:/config/

  hstream-storage:
    image: hstreamdb/hstream
    command: ld-dev-cluster --root /data/store --use-tcp
    volumes:
      - ./dbdata:/data/store

  hstream-server:
    image: hstreamdb/hstream
    command: hstream-server --port 6570 --store-config /data/store/logdevice.conf
    ports:
      - "6570:6570"
    volumes:
      - ./dbdata:/data/store
    depends_on:
      - hstream-storage

